pipelines:
    - name: go_app_build
      type: Bash
      configuration:
        runtime:
          type: image
          image:
            auto:
              language: go
              versions:
                - "1.17"
