pipelines:
  - name : pipe1
    steps:
      - name: new_cypress
        type: Matrix
        stepMode: Bash
        configuration:
          affinityGroup: group4
          runtime:
            type: image
            image:
              custom:
                registry: docker_registry
                sourceRepository: docker-registry
                name: test.mycompany.io/docker-registry/cypress/base
                tag: 14.18.1
