resources:
  - name: helmChartResource
    type: HelmChart
    configuration: 
      sourceArtifactory: #your artifactory integration
      repository: helm-local/
      chart: test
      version: 1.0.0
pipelines: 
  - name: helmBlueGreenDeployPipeline
    steps:
      - name: helmDeployStep
        type: HelmBlueGreenDeploy
        configuration: 
          helmVersion: 3
          namespace: app-namespace
          blueReleaseName: app-blue
          greenReleaseName: app-green
          roleServices:
            - blueReferenceName: app-blue-service
              greenReferenceName: app-green-service 
              idleName: app-idle-service
              liveName: app-service
          integrations:
            - name: pipe_ai_kuberentes
          inputResources:
            - name: helmChartResource
     
      - name: helmRoleSwitch
        type: HelmBlueGreenRoleSwitch
        configuration: 
          deployStep: helmDeployStep
          integrations:
            - name: pipe_ai_kuberentes
          inputSteps:
            - name: helmDeployStep   

      - name: helmCleanup
        type: HelmBlueGreenCleanup
        configuration: 
          deployStep: helmDeployStep
          integrations:
            - name: pipe_ai_kuberentes
          inputSteps:
            - name: helmRoleSwitch
