pipelines:
  - name: step_A
    type: Bash
    configuration:
      allowFailure: boolean         #optional
      inputSteps:
        - name: step_B
          status:
            - success
        - name: step_C
          status:
            - failure
            - skipped
            - cancelled
