pipelines:
      - name: test
        steps :
          - name: step1
            stepMode: Bash
            configuration:
              inputSteps:
                - name: setup
            stepletMultipliers:
              environmentVariables:
                - module: mod_1
                - module: mod_2
                - module: mod_3
                - module: mod_4
              runtimes:
                - type: image
                  image:
                    auto:
                      language: node
                      versions:
                        - 12
                - type: image
                  image:
                    auto:
                      language: node
                      versions:
                        - 8.17.0                    
            execution:
              onExecute:
                - pushd ./setup/app
                - MODULE="$module" npm run test
                - popd
              onComplete:
                - save_tests ./setup/app/reports
