pipelines:
  - name: step_A
    steps:  # Add the 'steps' section
      - name: step_B
        type: Bash
        status:
          - success
      - name: step_C
        type: Bash
        status:
          - failure
          - skipped
          - cancelled
