pipelines:
  - name: pipe1
    steps : 
      - name: pipe_step
        type: Bash
    configuration: 
      runtime:       
        type: image
        image:
          custom:
            name: docker/jfrog_win
            tag: latest
            options: "-e HOME=/root"
            autoPull: false
            registry: docker_registry
