pipelines:
  - name: S_Matrix_0052
    steps:           
      - name: S_Matrix_0052
        type: Matrix
        stepMode: Bash
        stepletMultipliers:
          fastFail: true
          allowFailures:
            - environmentVariables:
                delay: 1
                fail: 'true'
              nodePool: windows
              runtime: host
            - environmentVariables:
                delay: 1
                fail: 'true'
              nodePool: ubuntu
              runtime: host
          exclude:
            - environmentVariables:
                delay: 1
                fail: 'true'
              nodePool: windows
              runtime: host
            - environmentVariables:
                delay: 1
                fail: 'true'
              nodePool: ubuntu
              runtime: host 
          environmentVariables:
            - delay: 1
              fail: 'true'
            - delay: 2
              fail: 'false'
            - delay: 3
              fail: 'false'
            - delay: 5
              fail: 'false' 
        execution:
          onStart:
            - sleep "$delay"
          onExecute:
            - echo "I am on matrix step"
            - |
              [ $fail == 'false' ] 
            - ls -l .
