resources:
  - name: myApplication
    type: FileSpec
    configuration:
      sourceArtifactory: mkartifactory
      buildName: myBuild
      buildNumber: 1
  - name: myVM
    type: VmCluster
    configuration:
      sshKey: pipe_ai_test
      targets:
        - 0.0.0.0
        - 1.1.1.1
pipelines: 
  - name: linuxVMDeployPipeline
    steps:
      - name: linuxVMDeploy
        type: LinuxVMDeploy
        configuration:
          inputResources:
            - name: myVM
            - name: myApplication
          sshUser: myUser
          scripts:
            - name: deployCommand
              context: targetCluster 
              commands:
                - "./myApp"
          onFailure:
            - "if [ '$current_command' == 'deployCommand' ]; then ./doRollback.sh fi"
