pipelines:
  - name: pipe2
    steps:
        - name : sample_pipe
          type : Bash
          configuration: 
              runtime:       
                type: image
                image:
                  custom:
                    name: ubuntu
                    tag: latest
                    registry: myArtifactory
                    sourceRepository: docker-local
          execution:  # Add the 'execution' section
            onExecute:
              - echo "Runtime images "
