pipelines:
  - name: test
    step :
       - name: step1
         type: Matrix     
         stepMode: Bash
         stepletMultipliers:
         environmentVariables:
           - module: mod_1
           - module: mod_2
           - module: mod_3
           - module: mod_4
         runtimes: 
           - type: image
             image:
               auto:
                 language: node
                 versions:
                   - 12
           - type: image
             image:
               auto:
                 language: node
                 versions:
                   - 8.17.0         
