resources:
  - name: myFileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: mkartifactory
pipelines: 
  - name: uploadArtifactPipeline
    steps:
      - name: uploadArtifactStep
        type: UploadArtifact
        configuration:
          targetPath: my-repository/myDirectory/myFile.txt
          autoPublishBuildInfo: true
          forceXrayScan: true
          integrations:
            - name: mkartifactory
          inputResources:
            - name: myFileSpec
          outputResources:
            - name: myBuildInfo
