
resources:
  - name: app_test_results
    type: PropertyBag
    configuration:
      passing: 0
      failing: 0
  - name: app_docker
    type: Image
    configuration:
      registry: docker_registry
      sourceRepository: docker-local        # replace with your repository name
      imageName: docker.artprod.mycompany.com/baseimage
      imageTag: latest
      autoPull: true
pipelines:
    - name: test_app
      steps :
        - name: pipe1
          type: Jenkins
          configuration:
           jenkinsJobName: basic-api
           inputResources:
             - name: app_docker
           buildParameters:
             imageName: $res_app_docker_imageName
             imageTag: $res_app_docker_imageTag
           integrations:
             - name: pipe_ai_jenkins
           outputResources:
             - name: app_test_results
