pipelines:
  - name: step_A
    steps:  # Add the 'steps' section
      - name: step_B
        type: Bash
        execution :
          onExecute:
            - echo 'success'
      - name: step_C
        type: Bash
        execution :
          onExecute:
            - echo 'success'
