pipelines:
  - name: step_A
    steps:
      - name: step_B
        type: Bash
        configuration:
          # Add your Bash commands here
        status:
          - success
      - name: step_C
        type: Bash
        configuration:
          # Add your Bash commands here
        status:
          - failure
          - skipped
          - cancelled
