pipelines:
  - name: pipeline_1
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: node
            version: "18" # Either "version" or "versions" can be used.
            versions:
              - "18"
