resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: mkgithub
      path:  Manokarthi2412/python-lint
      branches:
        include: main  # Replace with the branch you want to use

pipelines:
  - name: run_script
    steps:
      - name: run_python_script
        type: Bash
        configuration:
          inputResources:
            - name: git_repo
        execution:
          onExecute:
            # - pushd $res_git_repo_python_resourcePath
            # - python3 -m pip install --upgrade pip
            # - pip install -r requirements.txt
            # - python3 -m pip install chromadb
            # - ls
            # - python3 validation.py  # Replace with the actual path to your Python script
            - echo "Hello world"
            - curl -X GET "10.90.127.215:5777/validate"
