resources:
  - name: myApplication
    type: FileSpec
    configuration:
      sourceArtifactory: myArtifactory
      pattern: "example-repo-local/myApp"
  - name: myVM
    type: VmCluster
    configuration:
      sshKey: s_VM_DEPLOY_SSHKEY
      targets:
        - 0.0.0.0
        - 1.1.1.1
pipelines:
  - name: linuxVMDeployPipeline
    steps:
      - name: linuxVMDeploy
        type: LinuxVMDeploy
        configuration:
          environmentVariables:
            deploy_targets_override: "123.456.78.90,127.0.0.1"
          inputResources:
            - name: myVM
            - name: myApplication
          sshUser: myUser
          scripts:
            - name: deployCommand
              context: targetCluster 
              commands:
                - "./myApp"
