pipelines:
  - name: pipe3
    steps:
      - name : sample_pipe
        type : Bash
        configuration: 
          runtime:       
            type: image
            image:
              custom:
                name: 541601.dkr.ecr.us-east-1.amazonaws.com/jfbeta
                tag: latest
                autoPull: false
                registry: AWS
                region: us-east-1
          execution:  # Add the 'execution' section
            onExecute:
              - echo "Runtime images "
