pipelines:
    - name: node_app_build
      type: Bash
      configuration:
        runtime:
          type: image
          image:
            auto:
              language: node
              versions:
                - "14.19.1"
